services:
  api:
    build:
      context: .
      dockerfile: scripts/Dockerfile.scanning
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./yara_rules:/app/yara_rules
    environment:
      - DATABASE_URL=sqlite:///app/data/email_analysis.db
    restart: unless-stopped

  # Optional: Redis for future job queue
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Web UI
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8080
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - default

  # Optional: ClamAV daemon (if needed separately)
  clamav:
    image: clamav/clamav:stable
    platform: linux/amd64
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    restart: unless-stopped

volumes:
  clamav_data: